### PR TITLE
Allow workshop content to open specific file and line in editor

### PR DESCRIPTION
**Pull request by kdvolder**
This addresses bullet point 1 from https://github.com/eduk8s-tests/lab-spring-boot-k8s-getting-started/issues/1

I.e. opening a specific file in the IDE.

See the top of 'intro.md' for an example of this is supposed to be used.

Thanks to @GrahamDumpleton for helping us sort out proper way to 'glue' the `eduk8s-vscode-helper` extension into eduk8s.
(Details here: https://github.com/eduk8s-tests/lab-spring-boot-k8s-getting-started/pull/6)

His PR was merged into our branch and is included into this PR.

@dsyer I did not want to merge this code directly into master as I am uncertain how you are using the master branch ATM and waned to avoid accidentally disrupting your workflow. If you feel okay with it... please go ahead and merge this into master (or let me know and I'll do it myself).

### CODE REVIEW

**Comment by GrahamDumpleton** [comment]
Need to remove the pesky ``.DS_Store`` file which got added to git. Not sure how that managed to get added since usually that file type is in global git ignore defaults.

**Comment by kdvolder** [comment]
@dsyer okay to merge this? Or do you prefer to keep this and future work on 'editor remote control' features in branch for the time being?

**Comment by dsyer** [comment]
Stick it on master. That way I can try it.

**Comment by GrahamDumpleton** [comment]
You will want to ensure on latest eduk8s operator and revise your budget setting, using instead new ability to override limit ranges.

https://docs.eduk8s.io/en/latest/runtime-environment/workshop-definition.html#resource-budget-for-namespaces

**Comment by kdvolder** [comment]
@GrahamDumpleton What is the difference between this (from your fixes to our branch):

```
  session:
    budget: large
```

And (From the docs link):

```
  session:
    namespaces:
      budget: large
```

And why do we want to change it?

Also, I think Dave is using the eduk8s instance hosted by eduk8s team. So probably doesn't need to worry about updating the operator. However, the instance we are/were using is our own, and I'm not sure on the best way to update the operator. Is it sufficient to just re-run all the various 'kubectl apply' commands? Or is there a nice script somewhere to update the operator?

**Comment by GrahamDumpleton** [comment]
Use of:

```
  session:
    budget: large
```

is going away. Deprecated in favour of:

```
  session:
    namespaces:
      budget: large
```

In adding limits stuff, it made better naming sense to group under both settings under ``namespaces`` section so was clearer what it applied to.

As to upgrade, running:

```
kubectl apply -k "github.com/eduk8s/eduk8s?ref=master"
```

again should technically update things okay. The existing TrainingPortal which is deployed will be using the same portal image it was though, so would need to delete/recreate the TrainingPortal to update it.

**Pull request merged**
